package com.itemOrder.model;
// Generated 2022�~1��16�� �U��5:27:19 by Hibernate Tools 5.4.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.member.model.MemberVO;

/**
 * ItemOrder generated by hbm2java
 */
public class ItemOrderVO implements java.io.Serializable {

	private Integer orderNo;
	private MemberVO memberVO;
	private Date tranTime;
	private Integer orderTotal;
	private int orderState;
	private String receiverName;
	private String receiverAddress;
	private String receiverPhone;
	private Set itemDetails = new HashSet(0);

	public ItemOrderVO() {
	}

	public ItemOrderVO(MemberVO memberVO, Date tranTime, int orderState, String receiverName, String receiverAddress,
			String receiverPhone) {
		this.memberVO = memberVO;
		this.tranTime = tranTime;
		this.orderState = orderState;
		this.receiverName = receiverName;
		this.receiverAddress = receiverAddress;
		this.receiverPhone = receiverPhone;
	}

	public ItemOrderVO(MemberVO memberVO, Date tranTime, Integer orderTotal, int orderState, String receiverName,
			String receiverAddress, String receiverPhone, Set itemDetails) {
		this.memberVO = memberVO;
		this.tranTime = tranTime;
		this.orderTotal = orderTotal;
		this.orderState = orderState;
		this.receiverName = receiverName;
		this.receiverAddress = receiverAddress;
		this.receiverPhone = receiverPhone;
		this.itemDetails = itemDetails;
	}

	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	public MemberVO getMemberVO() {
		return memberVO;
	}

	public void setMemberVO(MemberVO memberVO) {
		this.memberVO = memberVO;
	}

	public Date getTranTime() {
		return this.tranTime;
	}

	public void setTranTime(Date tranTime) {
		this.tranTime = tranTime;
	}

	public Integer getOrderTotal() {
		return this.orderTotal;
	}

	public void setOrderTotal(Integer orderTotal) {
		this.orderTotal = orderTotal;
	}

	public int getOrderState() {
		return this.orderState;
	}

	public void setOrderState(int orderState) {
		this.orderState = orderState;
	}

	public String getReceiverName() {
		return this.receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}

	public String getReceiverAddress() {
		return this.receiverAddress;
	}

	public void setReceiverAddress(String receiverAddress) {
		this.receiverAddress = receiverAddress;
	}

	public String getReceiverPhone() {
		return this.receiverPhone;
	}

	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	public Set getItemDetails() {
		return this.itemDetails;
	}

	public void setItemDetails(Set itemDetails) {
		this.itemDetails = itemDetails;
	}

}