package com.item.model;
// Generated 2022�~1��16�� �U��5:27:19 by Hibernate Tools 5.4.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.validation.constraints.NotEmpty;

import org.springframework.format.annotation.DateTimeFormat;

import com.productKind.model.ProductKindVO;

/**
 * Item generated by hbm2java
 */
public class ItemVO implements java.io.Serializable {

	private Integer itemNo;
	private ProductKindVO productKindVO;
	private String itemName;
	private Integer itemPrice;
	private Integer itemState;
	private Date soldTime;
	private Date launchedTime;
	private BigDecimal warrantyDate;
	private String itemProdDescription;
	private Integer Quantity;
	private Set itemPics = new HashSet(0);
	private Set itemDetails = new HashSet(0);

	public ItemVO() {
	}

	public ItemVO(ProductKindVO productKindVO, String itemName, Date launchedTime, BigDecimal warrantyDate,
			String itemProdDescription) {
		this.productKindVO = productKindVO;
		this.itemName = itemName;
		this.launchedTime = launchedTime;
		this.warrantyDate = warrantyDate;
		this.itemProdDescription = itemProdDescription;
	}

	public ItemVO(ProductKindVO productKindVO, String itemName, Integer itemPrice, Integer itemState, Date soldTime,
			Date launchedTime, BigDecimal warrantyDate, String itemProdDescription, Set itemPics, Set itemDetails) {
		this.productKindVO = productKindVO;
		this.itemName = itemName;
		this.itemPrice = itemPrice;
		this.itemState = itemState;
		this.soldTime = soldTime;
		this.launchedTime = launchedTime;
		this.warrantyDate = warrantyDate;
		this.itemProdDescription = itemProdDescription;
		this.itemPics = itemPics;
		this.itemDetails = itemDetails;
	}

	
	public Integer getQuantity() {
		return Quantity;
	}

	public void setQuantity(Integer quantity) {
		Quantity = quantity;
	}

	public Integer getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Integer itemNo) {
		this.itemNo = itemNo;
	}
	
	public ProductKindVO getProductKindVO() {
		return productKindVO;
	}

	public void setProductKindVO(ProductKindVO productKindVO) {
		this.productKindVO = productKindVO;
	}
	
	@NotEmpty(message="商品名稱: 請勿空白")
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Integer getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Integer itemPrice) {
		this.itemPrice = itemPrice;
	}

	public Integer getItemState() {
		return this.itemState;
	}

	public void setItemState(Integer itemState) {
		this.itemState = itemState;
	}
	
	@DateTimeFormat(pattern="yyyy-MM-dd") 
	public Date getSoldTime() {
		return this.soldTime;
	}

	public void setSoldTime(Date soldTime) {
		this.soldTime = soldTime;
	}

	@DateTimeFormat(pattern="yyyy-MM-dd") 
	public Date getLaunchedTime() {
		return this.launchedTime;
	}

	public void setLaunchedTime(Date launchedTime) {
		this.launchedTime = launchedTime;
	}

	public BigDecimal getWarrantyDate() {
		return this.warrantyDate;
	}

	public void setWarrantyDate(BigDecimal warrantyDate) {
		this.warrantyDate = warrantyDate;
	}

	public String getItemProdDescription() {
		return this.itemProdDescription;
	}

	public void setItemProdDescription(String itemProdDescription) {
		this.itemProdDescription = itemProdDescription;
	}

	public Set getItemPics() {
		return this.itemPics;
	}

	public void setItemPics(Set itemPics) {
		this.itemPics = itemPics;
	}

	public Set getItemDetails() {
		return this.itemDetails;
	}

	public void setItemDetails(Set itemDetails) {
		this.itemDetails = itemDetails;
	}

}

	