package com.productKind.model;

import java.util.HashSet;
import java.util.Set;

/**
 * ProductKind generated by hbm2java
 */
public class ProductKindVO implements java.io.Serializable {

	private Integer kindNo;
	private String kindName;
	private Set items = new HashSet(0);

	public ProductKindVO() {
	}

	public ProductKindVO(String kindName) {
		this.kindName = kindName;
	}

	public ProductKindVO(String kindName, Set items) {
		this.kindName = kindName;
		this.items = items;
	}

	public Integer getKindNo() {
		return this.kindNo;
	}

	public void setKindNo(Integer kindNo) {
		this.kindNo = kindNo;
	}

	public String getKindName() {
		return this.kindName;
	}

	public void setKindName(String kindName) {
		this.kindName = kindName;
	}

	public Set getItems() {
		return this.items;
	}

	public void setItems(Set items) {
		this.items = items;
	}

}
