package com.transRec.model;
//Generated 2022�~1��16�� �U��5:27:19 by Hibernate Tools 5.4.12.Final

import java.util.Date;

import com.member.model.MemberVO;

/**
* TransRec generated by hbm2java
*/
public class TransRecVO implements java.io.Serializable {

	private Integer transRecNo;
	private MemberVO memberVO;
	private int transAmount;
	private Date transRecTime;
	private int transState;
	private String mallName;
	private Integer orderNo;
	private String transCont;

	public TransRecVO() {
	}

	public TransRecVO(MemberVO memberVO, int transAmount, Date transRecTime, int transState, String mallName, String transCont) {
		this.memberVO = memberVO;
		this.transAmount = transAmount;
		this.transRecTime = transRecTime;
		this.transState = transState;
		this.mallName = mallName;
		this.transCont = transCont;
	}

	public TransRecVO(MemberVO memberVO, int transAmount, Date transRecTime, int transState, String mallName, Integer orderNo,
			String transCont) {
		this.memberVO = memberVO;
		this.transAmount = transAmount;
		this.transRecTime = transRecTime;
		this.transState = transState;
		this.mallName = mallName;
		this.orderNo = orderNo;
		this.transCont = transCont;
	}

	public Integer getTransRecNo() {
		return this.transRecNo;
	}

	public void setTransRecNo(Integer transRecNo) {
		this.transRecNo = transRecNo;
	}

	public MemberVO getMemberVO() {
		return memberVO;
	}

	public void setMemberVO(MemberVO memberVO) {
		this.memberVO = memberVO;
	}

	public int getTransAmount() {
		return this.transAmount;
	}

	public void setTransAmount(int transAmount) {
		this.transAmount = transAmount;
	}

	public Date getTransRecTime() {
		return this.transRecTime;
	}

	public void setTransRecTime(Date transRecTime) {
		this.transRecTime = transRecTime;
	}

	public int getTransState() {
		return this.transState;
	}

	public void setTransState(int transState) {
		this.transState = transState;
	}

	public String getMallName() {
		return this.mallName;
	}

	public void setMallName(String mallName) {
		this.mallName = mallName;
	}

	public Integer getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(Integer orderNo) {
		this.orderNo = orderNo;
	}

	public String getTransCont() {
		return this.transCont;
	}

	public void setTransCont(String transCont) {
		this.transCont = transCont;
	}

}
