package com.itemPic.model;
//Generated 2022�~1��16�� �U��5:27:19 by Hibernate Tools 5.4.12.Final

import com.item.model.ItemVO;

/**
* ItemPic generated by hbm2java
*/
public class ItemPicVO implements java.io.Serializable {

	private Integer itemPicNo;
	private ItemVO itemVO;
	private byte[] itemPic;

	public ItemPicVO() {
	}

	public ItemPicVO(ItemVO itemVO, byte[] itemPic) {
		this.itemVO = itemVO;
		this.itemPic = itemPic;
	}

	public Integer getItemPicNo() {
		return this.itemPicNo;
	}

	public void setItemPicNo(Integer itemPicNo) {
		this.itemPicNo = itemPicNo;
	}


	public ItemVO getItemVO() {
		return itemVO;
	}

	public void setItemVO(ItemVO itemVO) {
		this.itemVO = itemVO;
	}

	public byte[] getItemPic() {
		return this.itemPic;
	}

	public void setItemPic(byte[] itemPic) {
		this.itemPic = itemPic;
	}

}
