package com.itemDetail.model;
//Generated 2022�~1��16�� �U��5:27:19 by Hibernate Tools 5.4.12.Final

import com.item.model.ItemVO;
import com.itemOrder.model.ItemOrderVO;

/**
* ItemDetail generated by hbm2java
*/
public class ItemDetailVO implements java.io.Serializable {

	private ItemDetailId id;
	private ItemVO itemVO;
	private ItemOrderVO itemOrderVO;
	private Integer itemSales;
	private Integer itemPrice;

	public ItemDetailVO() {
	}

	public ItemDetailVO(ItemDetailId id, ItemVO itemVO, ItemOrderVO itemOrderVO) {
		this.id = id;
		this.itemVO = itemVO;
		this.itemOrderVO = itemOrderVO;
	}

	public ItemDetailVO(ItemDetailId id, ItemVO itemVO, ItemOrderVO itemOrderVO, Integer itemSales, Integer itemPrice) {
		this.id = id;
		this.itemVO = itemVO;
		this.itemOrderVO = itemOrderVO;
		this.itemSales = itemSales;
		this.itemPrice = itemPrice;
	}

	public ItemDetailId getId() {
		return this.id;
	}

	public void setId(ItemDetailId id) {
		this.id = id;
	}

	public ItemVO getItemVO() {
		return itemVO;
	}

	public void setItemVO(ItemVO itemVO) {
		this.itemVO = itemVO;
	}

	public ItemOrderVO getItemOrderVO() {
		return itemOrderVO;
	}

	public void setItemOrderVO(ItemOrderVO itemOrderVO) {
		this.itemOrderVO = itemOrderVO;
	}

	public Integer getItemSales() {
		return this.itemSales;
	}

	public void setItemSales(Integer itemSales) {
		this.itemSales = itemSales;
	}

	public Integer getItemPrice() {
		return this.itemPrice;
	}

	public void setItemPrice(Integer itemPrice) {
		this.itemPrice = itemPrice;
	}

}
